baseURL = 'https://cozycapybaragames.github.io/'
languageCode = 'hu-hu'
title = 'Cozy Capybara Games'
theme = 'hello-friend-ng'
enableGitInfo = true
timeZone = 'Europe/Budapest'

[params]
    homeSubtitle = 'Dokumentáció, ismeretterjesztő szövegek, "tananyag", stb.'
    enableSharingButtons = true
    customCSS = ['/css/styles.css']
    enableThemeToggle = true
    gitUrl = 'https://github.com/cozycapybaragames/cozycapybaragames.github.io/commit/'
    
[params.logo]
    logoText = 'Főoldal'
    logoCursorColor = '#eb4b42' 

[params.portrait]
    path = 'logo.png'
    maxWidth = '280px'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
    [[menu.main]]
       identifier = 'Haxe'
       name = 'Haxe'
       url = '/haxe' 